static char smbsubs[][50] = {
{"3 Count Bout"}, 
{"ADK World"}, 
{"Aero Fighters 2"}, 
{"Aero Fighters 3"}, 
{"Aggressors Of Dark Kombat"}, 
{"Alpha Mission 2"}, 
{"Art Of Fighting"}, 
{"Art Of Fighting 2"}, 
{"Art Of Fighting 3"}, 
{"Baseball Stars 2"}, 
{"Baseball Stars Professional"}, 
{"Blue's Journey"}, 
{"Breakers"}, 
{"Burning Fight"}, 
{"Bust-A-Move"}, 
{"Crossed Swords"}, 
{"Crossed Swords 2"}, 
{"Cyber-Lip"}, 
{"Double Dragon"}, 
{"Fatal Fury"}, 
{"Fatal Fury 2"}, 
{"Fatal Fury 3"}, 
{"Fatal Fury Special"}, 
{"Fighter's History Dynamite"}, 
{"Football Frenzy"}, 
{"Galaxy Fight"}, 
{"Ghost Pilots"}, 
{"IronClad"}, 
{"Joy Joy Kid"}, 
{"Kabuki Klash"}, 
{"King Of Fighters 94"}, 
{"King Of Fighters 95"}, 
{"King Of Fighters 96"}, 
{"King Of Fighters 96 - Neo Geo Collection"}, 
{"King Of Fighters 97"}, 
{"King Of Fighters 98"}, 
{"King Of Fighters 99"}, 
{"King Of The Monsters 2"}, 
{"Last Blade"}, 
{"Last Blade 2"}, 
{"Last Resort"}, 
{"League Bowling"}, 
{"Magical Drop 2"}, 
{"Magician Lord"}, 
{"Mahjong Final Romance 2"}, 
{"Mahjong Kyo Retsuden"}, 
{"Master Of Syougi"}, 
{"Metal Slug"}, 
{"Metal Slug 2"}, 
{"Mutation Nation"}, 
{"Nam 1975"}, 
{"Neo Drift Out"}, 
{"Neo Geo CD Special"}, 
{"Neo Turf Masters"}, 
{"Ninja Combat"}, 
{"Ninja Commando"}, 
{"Ninja Master's"}, 
{"Over Top"}, 
{"Pleasuregoal - 5on5 Mini Soccer"}, 
{"Power Spikes 2"}, 
{"Pulstar"}, 
{"Quest Of Jong Master"}, 
{"Quiz King Of Fighters"}, 
{"Ragnagard"}, 
{"Rally Chase"}, 
{"Real Bout Fatal Fury"}, 
{"Real Bout Fatal Fury 2"}, 
{"Real Bout Fatal Fury Special"}, 
{"Riding Hero"}, 
{"Robo Army"}, 
{"Samurai Shodown"}, 
{"Samurai Shodown 2"}, 
{"Samurai Shodown 3"}, 
{"Samurai Shodown 4"}, 
{"Samurai Spirits RPG"}, 
{"Savage Reign"}, 
{"Sengoku"}, 
{"Sengoku 2"}, 
{"Soccer Brawl"}, 
{"Stakes Winner"}, 
{"Street Slam"}, 
{"Super Baseball 2020"}, 
{"Super Sidekicks"}, 
{"Super Sidekicks 2"}, 
{"Super Sidekicks 3"}, 
{"Super Spy"}, 
{"Top Hunter"}, 
{"Top Player's Golf"}, 
{"Twinklestar Sprites"}, 
{"Viewpoint"}, 
{"Voltage Fighter Gowcaizer"}, 
{"Windjammers"}, 
{"World Heroes"}, 
{"World Heroes 2"}, 
{"World Heroes 2 Jet"}, 
{"World Heroes Perfect"}, 
{"Zintrick"}, 
{""}
};
